# These are supported funding model platforms

custom: ['https://www.paypal.com/donate?hosted_button_id=LMW4URER3SYYW', 'https://yuetloo.github.io/zkpayment/#network=ropsten&to=0xCc50960d6Ff869EaC6e07588477bfA32aD1aF49E']
